In [2]:
import numpy as np
%pip install sympy scipy
import scipy as sp
from sympy import Matrix


  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
ERROR: umap-learn 0.5.1 has requirement numba>=0.49, but you'll have numba 0.48.0 which is incompatible.
ERROR: torchvision 0.18.1 has requirement torch==2.3.1, but you'll have torch 2.1.1 which is incompatible.
ERROR: tensorflow 2.3.1 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.24.4 which is incompatible.
ERROR: scikit-image 0.21.0 has requirement networkx>=2.8, but you'll have networkx 2.4 which is incompatible.
ERROR: scikit-image 0.21.0 has requirement packaging>=21, but you'll have packaging 20.3 which is incompatible.
ERROR: scikit-image 0.21.0 has requirement pillow>=9.0.1, but you'll have pillow 7.0.0 which is incompatible.
ERROR: resampy 0.4.3 has requirement numba>=0.53, but you'll have numba 0.48.0 which is incompatible.
ERROR: pynndescent 0.5.13 has requirement numba>=0.51.2, but you'll have numba 0.48.0 which is incompatible.
ERROR: imageio 2.34.2 has requireme

/home/avery/.local/lib/python3.8/site-packages/scipy/__init__.py:143: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.17.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [5]:
A = np.array([[1,0,9,0,0,3],[0,0,0,0,-2,0],[0,1,3,-7,0,-7],[2,1,21,-7,-2,-1]])
#C = np.array([[-3,-5,-4],[6,10,8],[-12,-20,-16]])
#d = np.array([[0],[0],[0]])
pre_rref = Matrix(A)
post_rref = pre_rref.rref()
print(post_rref)
#linalg.solve(C, d)




(Matrix([
[1, 0, 9,  0, 0,  3],
[0, 1, 3, -7, 0, -7],
[0, 0, 0,  0, 1,  0],
[0, 0, 0,  0, 0,  0]]), (0, 1, 4))


In [6]:
#fuck it we dot product
import random
vec1 = np.array([2,-2,-3,0,1,99])
a = random.random()
print(a)
vec2 = np.array([-5,-3,a,-3,10,18])
dot = np.dot(vec1,vec2)

dotNew = dotNew = np.dot(vec1,vec2)
increment = 1
Dir = True

while(dot > 0.0000000001 or dot < -0.0000000001):
    print(a)
    dot = np.dot(vec1,vec2)
    if(Dir):
        a = a - increment
    else:
        a = a + increment
    vec2 = np.array([-5,-3,a,-3,10,18])
    dotNew = np.dot(vec1,vec2)

    if(abs(dot) < abs(dotNew) ):
        Dir = not Dir
        increment = increment/2
   

0.7948563748588162
0.7948563748588162
-0.20514362514118378
0.2948563748588162
0.7948563748588162
1.2948563748588162
1.7948563748588162
2.294856374858816
2.794856374858816
3.294856374858816
3.794856374858816
4.294856374858816
4.794856374858816
5.294856374858816
5.794856374858816
6.294856374858816
6.794856374858816
7.294856374858816
7.794856374858816
8.294856374858817
8.794856374858817
9.294856374858817
9.794856374858817
10.294856374858817
10.794856374858817
11.294856374858817
11.794856374858817
12.294856374858817
12.794856374858817
13.294856374858817
13.794856374858817
14.294856374858817
14.794856374858817
15.294856374858817
15.794856374858817
16.294856374858817
16.794856374858817
17.294856374858817
17.794856374858817
18.294856374858817
18.794856374858817
19.294856374858817
19.794856374858817
20.294856374858817
20.794856374858817
21.294856374858817
21.794856374858817
22.294856374858817
22.794856374858817
23.294856374858817
23.794856374858817
24.294856374858817
24.794856374858817
25.2948

In [1]:
#fuck it we dot product but this time we solving for a thing to scale the vector by :}
import random

vec1 = np.array([3,6])
vec2 = np.array([3,7])

dot = np.dot(vec1,vec2)
a = random.random() - 4
dotNew = np.dot(vec1,vec2)
increment = 1
Dir = True
while(dot > 0.000000001 or dot < -0.0000000001):
    dot = np.dot(vec1,vec2)
    if(Dir):
        a = a - increment
    else:
        a = a + increment
    vec2 = np.array([3,7])
    vec2 = vec2 - a*vec1 
    dotNew = np.dot(vec1,vec2)

    if(abs(dot) < abs(dotNew) ):
        Dir = not Dir
        increment = increment/2

NameError: name 'np' is not defined

8   -3  -44
15  -10 -100
0   -1   -4

In [8]:
A = np.array([[1,3,6],[2, 7, 14],[0, 2, 5]])
b = np.array([[-1],[3],[-4]])

print(A)
print(b)
linalg.solve(A,b)


[[ 1  3  6]
 [ 2  7 14]
 [ 0  2  5]]
[[-1]
 [ 3]
 [-4]]


array([[-16.],
       [ 33.],
       [-14.]])

In [9]:
u = np.array([-4,-3,-6])
v = np.array([2,-6,-5])

print(np.dot(u,v))
print(np.dot(v,u))

import math
def magnitude(vector): 
    return math.sqrt(sum(pow(element, 2) for element in vector))

print(magnitude(u)**2)
print(-3*np.dot(u,v))

print(np.dot((-3*u),v))
print(np.dot((u),(-3*v)))
print(np.dot(u,v)*v)

40
40
60.99999999999999
-120
-120
-120
[  80 -240 -200]


In [10]:
a = np.array([4,-5,-1])
b = np.array([-4,1,5])

print(np.arccos(np.dot(a,b)/(magnitude(a)*magnitude(b)))*180/np.pi)

128.246619878345


In [11]:

def angle_to_axis(vector):
    "returns angles of vectors to y axis in radians"
    angles = [(np.arccos(i/magnitude(vector))) for i in vector]
    return angles

In [12]:
v = np.array([6,2,5])
print(angle_to_axis(v))
magnitude(v)**2



[np.float64(0.7314473812549183), np.float64(1.3201094036718621), np.float64(0.9018322525264895)]


64.99999999999999

In [13]:
def angle_between_vectors(u, v):
    dot_product = sum(i*j for i, j in zip(u, v))
    norm_u = math.sqrt(sum(i**2 for i in u))
    norm_v = math.sqrt(sum(i**2 for i in v))
    cos_theta = dot_product / (norm_u * norm_v)
    angle_rad = math.acos(cos_theta)
    angle_deg = math.degrees(angle_rad)
    return angle_rad, angle_deg

In [14]:
a = np.array([8,-2,-5])
b = np.array([-3,8,-8])

def projection_of_vector(a,b):
    '''return projection of a onto b'''
    return [i*(np.dot(a,b)/(magnitude(b)**2)) for i in b] 

print(projection_of_vector(a,b))
print(a-projection_of_vector(a,b))
def component_of_vector(a,b):
    'returns component of a onto b'
    return (np.dot(b,a)/(magnitude(b)))

print(component_of_vector(a,b))

[np.float64(-0.0), np.float64(0.0), np.float64(-0.0)]
[ 8. -2. -5.]
0.0


In [15]:
#two forces with angles between them
a = np.array([9,0])
b = np.array([np.cos(132*np.pi/180)*11,np.sin(132*np.pi/180)*11])

print(magnitude(a+b))
c = a + b # c is the resulting vector by applying both forces to the same object
angle_between_vectors(c,a)


##that trucl ramp problem:


8.337394073746669


(1.3728544910965916, 78.65876822541516)

In [16]:
b = np.array([np.cos(52*np.pi/180)*37,np.sin(52*np.pi/180)*37])
b[0]*23

np.float64(523.9279155021352)

In [17]:
u = np.array([4,2,3])
v = np.array([0,3,3])

print(np.cross(u,v))
print(np.cross(v,u))
print(np.cross(u,u))
print(2*np.cross(u,v))
print(np.cross(u,2*v))
print(np.cross(u+v,v))

magnitude(np.cross(u,v))**2

[ -3 -12  12]
[  3  12 -12]
[0 0 0]
[ -6 -24  24]
[ -6 -24  24]
[ -3 -12  12]


297.0

In [18]:
a = np.array([4,5,-1])
b = np.array([0,1,3])
c = np.array([2,4,1])

np.dot(a,np.cross(b,c))

np.int64(-12)

In [ ]:
pq = np.array([-3-4,-1-6,0--4])
pr = np.array([-3-0,-1-6,0-6])

#magnitude(np.cross(pq,pr))

Fnet = np.array([6,16])

magnitude(Fnet)

np.arctan(16/6)*180/np.pi



np.float64(69.44395478041653)

In [5]:
sillyrabbitmatrixareforkids = np.array([[5, 4],[-1, 6]])
np.linalg.inv(sillyrabbitmatrixareforkids)
print(sillyrabbitmatrixareforkids)

[[ 5  4]
 [-1  6]]


In [20]:
sillyrabbitmatrixareforkids = np.array([[5, -3, 2],[1,-5,4],[11,-11,8]])
#np.linalg.inv(sillyrabbitmatrixareforkids)
sp.linalg.inv(sillyrabbitmatrixareforkids)
sillyrabbitmatrixareforkids = np.array([[3, -5], [-3, -4], [-1, 1]])
sp.linalg.lu(sillyrabbitmatrixareforkids)
#help(sp.linalg.lu)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.        ,  0.        ],
        [-1.        ,  1.        ],
        [-0.33333333,  0.07407407]]),
 array([[ 3., -5.],
        [ 0., -9.]]))

In [16]:

var('x')

testmat = np.array([[4,-1,0],[2,4,0],[2,-4,0]])

np.linalg.det(testmat)



0.0