In [ ]:
# Import NumPy
%pip install numpy
import numpy as np
import sympy as sp
from sympy import Matrix

# Define the matrix
A = np.array([[-1, 0, 4],
              [2, 1, -2],
              [9, 0, -6]])

# Compute the eigenvalues
eigenvalues, _ = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues of the matrix A:")
print(eigenvalues)

ERROR: Could not find a version that satisfies the requirement laguide (from versions: none)

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
ERROR: No matching distribution found for laguide
Note: you may need to restart the kernel to use updated packages.


ModuleNotFoundError: No module named 'laguide'

In [74]:
from sympy import Matrix

# Define the matrix
A = Matrix([[-2, 6, -12], 
            [0, 0, 0],
            [0, -2, 2]])
    
# Compute the eigenvalues and eigenvectors
eigenvalues = A.eigenvals()  # Eigenvalues as a dictionary {eigenvalue: multiplicity}
eigenvectors = A.eigenvects()  # Eigenvalues and corresponding eigenvectors

# Print the eigenvalues
print("Eigenvalues of the matrix A:")
for val, mult in eigenvalues.items():
    print(f"Eigenvalue: {val}, Multiplicity: {mult}")

# Print the eigenvectors
print("\nEigenvectors of the matrix A:")
for val, mult, vecs in eigenvectors:
    print(f"Eigenvalue: {val}")
    for vec in vecs:
        print(f"Eigenvector: {vec}")

# Diagonalization
P = A.diagonalize()[0]  # Matrix of eigenvectors
D = A.diagonalize()[1]  # Diagonal matrix of eigenvalues
P_inv = P.inv()  # Inverse of P

print("\nP (Matrix of eigenvectors):")
print(P)

print("\nD (Diagonal matrix of eigenvalues):")
print(D)

print("\nP^(-1) (Inverse of P):")
print(P_inv)

Eigenvalues of the matrix A:
Eigenvalue: 0, Multiplicity: 1
Eigenvalue: 2, Multiplicity: 1
Eigenvalue: -2, Multiplicity: 1

Eigenvectors of the matrix A:
Eigenvalue: -2
Eigenvector: Matrix([[1], [0], [0]])
Eigenvalue: 0
Eigenvector: Matrix([[-3], [1], [1]])
Eigenvalue: 2
Eigenvector: Matrix([[-3], [0], [1]])

P (Matrix of eigenvectors):
Matrix([[1, -3, -3], [0, 1, 0], [0, 1, 1]])

D (Diagonal matrix of eigenvalues):
Matrix([[-2, 0, 0], [0, 0, 0], [0, 0, 2]])

P^(-1) (Inverse of P):
Matrix([[1, 0, 3], [0, 1, 0], [0, -1, 1]])


In [75]:
A = np.array([[-2, 6, -12], 
              [0, 0, 0],
              [0, -2, 2]])

eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues of the matrix A:")
print(eigenvalues, '\n', eigenvectors)
print(np.diag(eigenvalues))
print(np.linalg.inv(eigenvectors))


Eigenvalues of the matrix A:
[-2.  2.  0.] 
 [[ 1.         -0.9486833  -0.90453403]
 [ 0.          0.          0.30151134]
 [ 0.          0.31622777  0.30151134]]
[[-2.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  0.]]
[[ 1.00000000e+00 -5.02428439e-16  3.00000000e+00]
 [ 0.00000000e+00 -3.16227766e+00  3.16227766e+00]
 [ 0.00000000e+00  3.31662479e+00  0.00000000e+00]]


In [78]:
A = np.array([[-2,18],[8,8]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of the matrix A:")
print(eigenvalues, '\n', eigenvectors)

Eigenvalues of the matrix A:
[-10.  16.] 
 [[-0.91381155 -0.70710678]
 [ 0.40613847 -0.70710678]]


In [85]:
A = np.array([[1,0,6], [-15,1,-99],[3,0,18]])
np.linalg.matrix_rank(A)
#A.shape[1]

np.int64(2)